config:
  model_kind: simple_cnn
  timm_name: resnet18
  epochs: 5
  batch_size: 256
  lr: 0.001
  device: cuda
  image_key: images
  target_hw: 75
  aug_flags:
  - hflip
  - vflip
  - rotate90
  max_blur_sigma: 1.5
  seed: 0
mode: supervised
created: '2025-12-15 19:10:39'
label_col: label
cluster_col: cluster
features_key: features
image_key: images
train_files:
- path: /mnt/deepstore/Vidur/Junk Classification/data/junk_annotated/oligo_junk.hdf5
  mode: fixed_1
  n: 8604
  n0: 0
  n1: 8604
- path: /mnt/deepstore/Vidur/Junk Classification/data/rare_cells_annotated/IM_CTCs_filter.hdf5
  mode: fixed_0
  n: 702
  n0: 702
  n1: 0
- path: /mnt/deepstore/Vidur/Junk Classification/data/rare_cells_annotated/ctcs.hdf5
  mode: fixed_0
  n: 321
  n0: 321
  n1: 0
- path: /mnt/deepstore/Vidur/Junk Classification/data/rare_cells_annotated/endos_cleaned.hdf5
  mode: fixed_0
  n: 210
  n0: 210
  n1: 0
- path: /mnt/deepstore/Vidur/Junk Classification/data/rare_cells_annotated/large_d_only.hdf5
  mode: fixed_0
  n: 569
  n0: 569
  n1: 0
- path: /mnt/deepstore/Vidur/Junk Classification/data/rare_cells_annotated/megas.hdf5
  mode: fixed_0
  n: 71
  n0: 71
  n1: 0
- path: /mnt/deepstore/Vidur/Junk Classification/data/rare_cells_annotated/oligo_clean.hdf5
  mode: fixed_0
  n: 4384
  n0: 4384
  n1: 0
- path: /mnt/deepstore/Vidur/Junk Classification/data/rare_cells_annotated/pc_ctcs.hdf5
  mode: fixed_0
  n: 181
  n0: 181
  n1: 0
- path: /mnt/deepstore/Vidur/Junk Classification/data/rare_cells_annotated/vim.hdf5
  mode: fixed_0
  n: 112
  n0: 112
  n1: 0
- path: /mnt/deepstore/Vidur/Junk Classification/data/wbcs_annotated/0ADD705_wbcs.hdf5
  mode: fixed_0
  n: 30059
  n0: 30059
  n1: 0
n_items_total: 45213
n_train: 28936
n_val: 7234
n_test: 9043
aug_flags:
- hflip
- vflip
- rotate90
max_blur_sigma: 1.5
