config:
  model_kind: simple_cnn
  timm_name: resnet18
  inputs_mode: image_only
  training_method: self-supervised
  loss_function: focal_loss
  epochs: 20
  batch_size: 256
  lr: 0.001
  device: cuda
  image_key: images
  mask_key: masks
  feature_key: features
  target_hw: 75
  aug_flags:
  - hflip
  - vflip
  - rotate90
  max_blur_sigma: 1.0
  seed: 0
job_name: simple_cnn | image_only | self-supervised | focal_loss
mode: self-supervised
inputs: image_only
